### ISSUE TITLE
Error on running ckan -c /etc/ckan/default/ckan.ini run in composite (Not enough values to unpack)

### ISSUE THREAD

**Issue by JOCKEEY** [espona/ckanext-composite#14]
Hi, I'm in the final stage to complete the installation of ckanext-composite but this error occur. I've already installed ckanext-scheming and ckanext-repeating. Any suggestion will much be appreciate.

```
(default) root@ccgeo:/usr/lib/ckan/default/src/ckanext-composite# ckan -c /etc/ckan/default/ckan.ini run
2021-11-18 07:00:00,726 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2021-11-18 07:00:00,726 INFO  [ckan.config.environment] Loading static files from public
2021-11-18 07:00:00,753 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2021-11-18 07:00:00,890 WARNI [ckanext.stats.stats] ckanext.stats does not support caching in current implementations
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
    ctx.obj = CkanCommand(value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 52, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 165, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 193, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 177, in update_config
    plugin.update_config(config)
  File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 131, in update_config
    self._load_presets(config)
  File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 116, in _load_presets
    _SchemingMixin._presets = {
  File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 119, in <dictcomp>
    for field in _load_schema(preset_path)['presets']
  File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 459, in _load_schema
    schema = _load_schema_module_path(url)
  File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 471, in _load_schema_module_path
    module, file_name = url.split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
(default) root@ccgeo:/usr/lib/ckan/default/src/ckanext-composite#

```

**Comment by JOCKEEY** [comment]
lol I just type
  `ckanext.composite.presets.json` instead of  `ckanext.composite:presets.json`
